version: '3.8'

services:
  server:
    image: botimage
    container_name: server
    restart: "unless-stopped"
    command: python -O src/app.py
    build:
      context: .
      dockerfile: Dockerfile

    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - "8080:8080"

  postgres:

    image: postgres:latest

    container_name: db
    restart: "unless-stopped"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./postgres:/var/lib/postgresql/data
